# Antecedentes

```{r echo=FALSE}
knitr::opts_chunk$set(out.width="80%", fig.pos = "!ht", out.extra = "")
```

Si bien se ha observado que el apoyo a la democracia en Chile ha sido históricamente alto [@navia2019], se deben notar con atención algunos síntomas que indican una caída en este respaldo [@cep]. Además, durante este último año se ha observado un fortalecimiento de la imagen pública de Augusto Pinochet y su dictadura [@cadem2023; @cerc-mori], así como de los últimos resultados electorales que han sido favorables para candidatos que han defendido abiertamente el legado del régimen militar y que han sido descritos como populistas radicales de derecha [@diaz2023]. Esto se da, además, en el contexto de una crisis de representatividad que se ha profundizado durante la última década, pero cuyos orígenes se pueden retrotraer incluso hacia fines de los años 90 [@luna2016]. 

La transición democrática chilena fue tempranamente considerada como exitosa, debido a su rápida consolidación institucional y económica, particularmente en comparación a procesos similares en otros países de América Latina [@odonnell1994]. En el resto de la región, por el contrario, se observaban dificultades en los procesos de consolidación de los nuevos regímenes, que fueron descritos por Guillermo O'Donnell [-@odonnell1994] bajo el concepto de *democracia delegativa*. Esta variante de democracia se caracterizaría por un presidente que es investido de un liderazgo fuerte que le permite pasar por sobre el control de otras instituciones del Estado con el fin de sanar y unir a la nación. En otras palabras, una democracia delegativa cuenta con una fuerte responsabilidad vertical (o *vertical accountability*), es decir, hacia el pueblo o los ciudadanos, pero no hacia otros poderes o instituciones (*horizontal accountability*) [@odonnell1994].

Esta descripción, por cierto, no se acomoda a la realidad chilena. Tampoco, sin embargo, se podría decir que Chile es plenamente una democracia representativa donde convivan ambas formas de rendición de cuentas. Por el contrario, lo que se observa es que la contundencia del control horizontal entre instituciones es acompañada por un profundo desarraigo entre las élites políticas y la ciudadanía [@luna2016].

En este contexto, si bien Chile no es una democracia delegativa, no sería raro pensar que aparezcan tendencias que apelen a una mayor rendición de cuentas vertical (por ejemplo, cumplir las promesas electorales), incluso a expensas de debilitar las instituciones de control horizontal, respaldando así soluciones autoritarias o no-democráticas [@carlin2018]

Por supuesto, la disminución del apoyo a la democracia y el surgimiento de opciones autoritarias o populistas no es un fenómeno únicamente local, y ha sido estudiado ampliamente en varias regiones del mundo bajo diversas etiquetas, tales como *liderazgos fuertes, no-democráticos o delegativos* [@carlin2011; @carlin2018; @crimston2022; @kang2018; @lima2021; @selvanathan2022; @xuereb2021], *populismos* [@baro2022; @gidron2020; @nowakowski2021], o *derecha populista radical* [@diaz2023; @donovan2019; @donovan2021]. También se ha puesto esfuerzos en identificar sus determinantes, entre los que se pueden contar factores culturales [@lima2021; @marchlewska2022; @selvanathan2022]; económicos objetivos y subjetivos [@arikan2019; @rico2020; @wu2019; @xuereb2021]; el bajo bienestar o estatus subjetivo [@gidron2020; @nowakowski2021]; sentimientos de anomia y de polarización moral [@crimston2022]; la pertenencia a una minoría étnica o religiosa con baja integración nacional [@eskelinen2020]; así como rasgos personales como el narcisismo [@marchlewska2019], la autoeficacia [@rico2020] o el privilegiar los valores de conservación [@baro2022].

En este contexto, pese a que el espectro Individualismo-Colectivismo se considera una de las más importantes y más estudiadas dimensiones de la cultura [@binder2019; @fatehi2020], y que ha sido utilizado como variable explicativa en diversos estudios sobre economía [@binder2019; @kyriacou2016; @germani2021; @toikko2020], capital social [@beilmann2018]; género [@dabiriyantehrani2022; @davis2019], familia [@al-hassan2021; @rudy2006], trabajo [@refslund2022; @solis2018; @stewart2020], cumplimiento de normas [@varet2018; @zhang2020], y actitudes frente a la pandemia y la vacunación [@card2022], su conexión con las preferencias políticas y el respaldo hacia distintos modelos de democracia aún ha sido escasamente explorada. 

Los conceptos de individualismo y colectivismo tienen un larga tradición intelectual, pero su auge actual en la literatura se remonta a los estudios de Hofstede sobre la cultura laboral en trabajadores de IBM en 39 países durante la década de 1980 [@oyserman2002]. Hofstede definió cuatro dimensiones culturales: "distancia de poder", "masculinidad", "aversión a la incertidumbre" e "individualismo", con esta última captando la mayor atención de los investigadores [@brewer2007]. 

Desde la conceptualización de Hofstede, Individualismo-Colectivismo -- definidos a un nivel cultural -- conforman los dos polos de un único espectro [@oyserman2002]. Las sociedades individualistas se caracterizarían por lazos poco estrechos entre individuos, de quienes se espera se hagan cargo de sí mismos y de su familia inmediata. La sociedades colectivistas, en tanto, se definen porque sus miembros están integrados desde su nacimiento a grupos fuertemente cohesionados que los protegen a lo largo de sus vidas a cambio de una lealtad incuestionada [@yoon2010]. 

Así, las investigaciones que han explorado la relación entre individualismo-colectivismo con actitudes política es más bien escasa y dispersa en el tiempo.  Al respecto, se ha descrito que entre estudiantes universitarios estadounidenses, el individualismo y colectivismo son dimensiones ortogonales, ubicando al primero, más bien, en el polo opuesto del autoritarismo [@gelfand1996]. En una serie de estudios comparativos en varios países, por otro lado, se han complejizado estos hallazgos, encontrando una asociación positiva entre autoritarismo e individualismo vertical -- que privilegia la competencia y jerarquía entre individuos -- pero no con el individualismo horizontal, que privilegia la competencia y la igualdad entre individuos [@kemmelmeier2003]. Se ha observado, además, que el individualismo vertical está asociado con orientaciones de dominancia social [@strunk1999] y con el voto conservador en los Estados Unidos [@zhang2009]. También se ha explorado la relación entre individualismo, colectivismo y autoritarismo a nivel familiar, encontrando que madres colectivistas apoyan un estilo más autoritario de parentalidad [@rudy2006]. Por otro lado, se ha argumentado que culturas individualistas promueven una mejor gobernanza, desincentivando la corrupción, el nepotismo y el clientelismo [@kyriacou2016].

Estos estudios comparten limitaciones, su carácter exploratorio, o el circunscribir las definiciones de individualismo y colectivismo a un nivel cultural, sin detenerse a analizar las posibles difracciones dentro de una misma sociedad. Además, ninguna de estas investigaciones ha explorado estos fenómenos en Chile o en América Latina. Tampoco se ha explorado la relación con el apoyo a una democracia delegativa que, si bien contiene rasgos autoritarios e iliberales, parece ser un fenómeno diferente [@carlin2011; @carlin2018]. De tal modo, se buscará abordar esa brecha incluyendo un giro en la conceptualización de individualismo, que busca pasar a entenderlo como el resultado de procesos sociohistóricos de individualización que difieren no solo entre culturas, sino también dentro de una misma sociedad [@martuccelli2018].

La individualización es una corriente sociohistórica que transforma las relaciones de los sujetos con la autoridad, así como los soportes y las modalidades que autorizan su ejercicio [@araujo2021]. Por ello, parece interesante indagar cómo diferentes variantes de individualismo -- resultado de difracciones de los procesos de individualización -- se relacionan con la pérdida de legitimidad de modalidades democráticas de autoridad, privilegiando, por ejemplo, liderazgos percibidos como más fuertes, eficientes [@araujo2022; @araujo2022a], o auténticos [@gauthier2021].

En visto de todo lo planteado, se propone como pregunta de investigación la siguiente: **¿Cuál es la relación entre distintos perfiles de individualismo y el apoyo a una democracia delegativa en la sociedad chilena?**

Lo que se traduce al objetivo general de **Establecer la relación entre distintos perfiles de individualismo y el apoyo a una democracia delegativa en la sociedad chilena**. A sus vez, de aquí se desprenden los siguientes objetivos específicos:

-   Identificar los perfiles de individualismo presentes en la sociedad chilena
-   Describir el nivel de apoyo a una democracia delegativa en la sociedad chilena
-   Relacionar las variantes de individualismo con el apoyo a una democracia delegativa en la sociedad chilena
