# Marco Teórico

## Democracia delegativa

El concepto de democracia delegativa fue acuñado por el sociólogo argentino Guillermo O'Donnell para describir la situación institucional de las nuevas democracias latinoamericanas surgidas tras el fin de los regímenes autoritarios en la región durante las décadas de 1980 y 1990. Esta forma de democracia se basa en la premisa de que el ganador de las elecciones presidenciales tiene derecho a gobernar sin restricciones, considerándose la encarnación del país y el principal defensor de sus intereses [@odonnell1994]. Se diferencian de las democracias representativas consolidadas en que una fuerte responsabilidad vertical (es decir, frente a sus electores) no es acompañada por una rendición de cuentas horizontal, esto es, hacia otras instituciones del Estado [@odonnell1994].

Bajo esta definición, Chile se ha tendido a tomar como un contraejemplo, destacando la fuerza de sus instituciones democráticas surgidas tras el fin de la Dictadura [@odonnell1994;@carlin2018]. Sin embargo, y como se ilustra en la tabla 1, en Chile la rendición de cuentas horizontal no es acompañada por una rendición de cuentas vertical, lo que se traduciría en una *Uprooted democracy* marcada por una profunda crisis de representatividad [@odonnell1994]. 

```{r, echo=F, message=F}
td <- c("Democracia Representativa",
                          "Democracia Delegativa",
                          "Democracia Desarraigada")

va <- c("+", "+", "-")
ha <- c("+", "-", "+")

tab1 <- data.frame(td, va, ha)

tab1 <- tab1 %>% rename("Tipo de democracia"=td,
                        "Vertical Accountability"= va,
                        "Horizontal Accountability"= ha)

tab1 %>%
  kable(
    format="latex",
    booktabs= TRUE,
    escape = FALSE,
    caption = "Comparación variantes democracia", align = "c") %>%
  row_spec(row=0, align = "c") %>%
  kable_styling(full_width = TRUE) %>% 
  footnote(general_title = "Nota.",
    general="Tabla basada en O'Donnell (1994) y en Luna (2016)",
    footnote_as_chunk = T) %>%   
  kable_classic(full_width = T, html_font = "Helvetica")

```

Frente a esto, no resulta contradictorio que una democracia caracterizada por su fuerza institucional puedan surgir en la población actitudades de preferencias por este tipo de gobierno [@carlin2011;@carlin2018]. Según Carlin [-@carlin2018], las personas que apoyan una democracia delegativa en Chile se caracterizan por apoyar a líderes fuertes que unan al país y lo guíen en tiempos de crissi, mostrar orientaciones no-liberales (*iliberals*) hacia los derechos políticos y falta de compromiso hacia los derechos humanos. Sin embargo, y quizás paradójicamente, este perfil sigue prefiriendo la democracia sobre otras formas de gobierno. 

Los liderazgos fuertes, de tal manera, se constituyen como una de las dimensiones fundamentales de las democracias delegativas. Subyace aquí la idea de una nación concebida como un ser orgánico, un verdadero Leviatán del que líder es su cabeza, y cuya función es "sanar la nación uniendo sus fragmentos dispersos en un todo harmonioso" [@odonnell1994, pp.60]. 

De lo anterior, se desprende un segunda característica esencial de esta vrariante de democracia. El líder, para cumplir su cometido, debe saber combinar elementos emocionales y carismáticos con otros altamente técnicos, precisamente bajo la justificación de "sanar" la nación [@odonnell1994]. Esta impronta tecnocrática mezclada con elementos emocionales no es del todo desconocidas en Chile, como se observaría en el tipo ideal portaliano [@araujo2013], una forma sociohistórica de ejercicio de la autoridad en Chile. Por otro lado, podría también recordar a la discusión sobre el surgimiento de actitudes tecnocráticas y tecnopopulistas en países europeos y su relación, muchas veces contradictoria, con la democracia [@chiru2022;@ganuza2020;@pilet2023].

## Individualismo

### Individidualismo-Colectivismo como una dimensión de la cultura

El fenómeno del individualismo ha sido abordado principalmente desde la psicología cultural, particularmente, de la comparación entre culturas, y generalmente en conjunto y oposición al colectivismo. Desde este punto de vista, de tal modo, existirían culturas (y, se debe notar, cultura se entiende casi siempre como sinónimo de países) que son individualista y otras que son colectivistas.

Los conceptos de individualismo y colectivismo tienen un larga tradición intelectual, pero su auge actual se remonta a los estudios de Hofstede sobre la cultura laboral en trabajadores de IBM en 39 países durante la década de 1980 [@oyserman2002]. Hofstede definió cuatro dimensiones culturales: "distancia de poder", "masculinidad", "aversión a la incertidumbre" e "individualismo", con esta última captando la mayor atención de los investigadores [@brewer2007]. 

Desde la conceptualización de Hofstede, Individualismo-Colectivismo -- definidos a un nivel cultural -- conforman los dos polos de un único espectro [@oyserman2002]. Las sociedades individualistas se caracterizan por lazos poco estrechos entre individuos, de quienes se espera se hagan cargo de si mismos y dde su familia inmediata. La sociedades colectivistas, en tanto, se caracterizar porque sus miembros están integrados desde su nacimiento a grupos fuertemente cohesionados que los protegen a lo largo de sus vida a cambio de una lealtad incuestionada [@yoon2010]. 

A pesar de que el propio Hofstede advierte que estas definiciones aplican 1) a un nivel cultural, pero no al individual; y 2) son procesos dinámicos en que las culturas pueden transformarse, estás recomendaciones no siempre han sido seguidas por los investigadores que han retomado esta perspectiva. Frente a esto, se han hecho intentos de elaborar conceptualizaciones alternativas, siendo la del *self-costrual* [@cross2011] una de las más populares. *Self-construal*, que puede ser traducido al español como autoconstrucción o autoconcepción, se refiere a las formas en que el individuo se concibe a sí mismo, ya sea de forma independiente o interdependiente sus grupos. Esta propuesta se diferencia de la de Hofstede en que es un constructo bidimensional. Ahora bien, pese a que se ha insistido que el *self-construal* y el individualismo-colectivismo son fenómenos diferentes, su operacionalización muchas veces se intercepta [@cross2011]. Por lo demás, se mantiene una interpretación más o menos explícita que relaciona una concepción independiente con culturas individualistas [@cross2011;@voronov2002]

Por otro lado, el uso de individualismo-colectivismo ha sido criticado por su falta de claridad conceptual, calificandolo como un concepto *catch-all*, que se ha por defecto para explicar diferencias culturales [@voronov2002]. Subyace aquí una dimensión normativa: El individualsimo se ha entendido como una dimensión esencial de la cultura estadounidense y anglosajana, y se asocia constantemente a la modernidad y al desarollo [@voronov2002; @wang2010]. Individualismo, así, suele tener una connotación positiva; colectivismo, una negativa [@moemeka1998], sobre todo en Estados Unidos y otros países anglosajones. De ahí que no sea de extrañar que individualismo y colectivismo puedan recordar, por ejemplo, las distinción que la sociología clásica estableció entre comunidad y sociedad, donde la primera "por su débil diferenciación social no daría lugar sino a una insuficiente individualización debido a que la semejanza entre sus miembros se impone" [@martuccelli2010, Segundo relato: Insuficiencias y anomalías, párrafo 2].

Esta falta de claridad conceptual queda patente en el metaestudio de Oyserman y colegas [-@oyserman2002], quienes a través de un análisis de contenido a las escalas más utilizadas para medir estos fenómenos puede referirse a hasta 6 cosas distintas (independencia, orientación al logro, competencia, unicidad, autoconocimiento y comunicación directa); mientras que colectivismo a otras 8 (relaciones, pertenencia, deber, armonía, búsqueda de consejo, contextualidad, jerarquía y grupos).  Brewer y Chen [-@brewer2007] van más allá, indicando que en realidad ni siquiera hay verdadera simetría en las formas en que individualismo y colectivismo están operacionalizados: Así, mientras que los ítem para medir el primero suelen referirse a la identidad y la agencia de los individuos; el segundo se suele medir como un sistema de valores. 

También se ha puesto atención a la falta de claridad de quiénes son los colectivos del colectivismo, no haciendo una clara distinción entre grupos, colectivos y comunidades. Un ejemplo de esta indefinición es el problema del familiarismo: La familia, de alguna forma u otra, se ha integrado en las definiciones y operacionalizaciones tanto de individualismo como de colectivismo [@oyserman2002]. 

Notoriamente, la definición de individualismo de Hofstede incluye una mención a la familia. Brewer y Venaik [-@brewer2011], además, agregar que la operacionalización de colectivismo poco tiene que ver con su conceptualización teórico. Frente a ello, proponen renombrar la escala como una que distingue, más bien, entre orientaciones personales (*self-orientation*) y orientaciones laborales (*work-orientation*). 

Para Moemeka [-@moemeka1998], los colectivos se forman por elección mientras que las comunidades son preexistentes a las personas. De ahí que no haya verdadera contradicción entre colectivismo e individualismo. Por ejemplo, los partidos políticos y movimientos sociales colectivos -- en fin, la sociedad civil entendida como el libre juego de los intereses individuales y privados [@arribas1999] -- tienen mayor típicamente mayor desarrollo en sociedades denominadas como individualistas. 

Frente a lo anterior, Moemeka [-@moemeka1998] apunta a que más que colectivismo se debería hablar de comunalismo. Con todo, Brewer y Chen [-@brewer2007], mediante un metanálisis, concluyen que las escalas más populares no miden comunidades, según lo definido por Moemeka, sino relaciones interpersonales. Por ello, proponen distinguir está dimensión de la colectiva propiamente tal, que se referiría a grupos enteros, sean étnicos, religiosos o nacionales. 

Estas brechas conceptuales podrían explicar las "anomalías" observadas en varios de estos estudios, como que los individualistas pueden ser tanto o más colectivistas que los colectivistas [@oyserman2002], o que en determinados contextos los colectivistas actúan de manera individualista [@voronov2002]. A nivel agregado, Chile podría considerarse como un claro ejemplo de estas incongruencias: Tradicionalmente entendida como una sociedad colectivista [@rojas2008], el colectivismo en Chile es alto [@oyserman2002], incluso más que en otras sociedades típicamente colectivistas como Corea del Sur. Pese a esto, los niveles de individualismo en Chile pueden ser incluso más altos que los observados en Estados Unidos [@oyserman2002] o Noruega [@kolstad2009].

Esto abre la pregunta de si Chile realmente es una sociedad colectivista, y si no lo es, ¿hasta que punto es que una sociedad individualista? Responder esta pregunta implica el riesgo de salir de un relato de insuficiencia ("Chile no es un país individualista"), solo para caer en un relato del *ni, ni* [@martuccelli2010]: "Chile no es *ni* individualista *ni* colectivista". Una afirmación correcta desde la perspectiva teórica hasta aquí esbozada, pero preocupantemente insuficiente en el esfuerzo de una descripción sociológica de la sociedad chilena.  

Para escapar de esta trampa es necesario dar un giro hacia una perspectiva teórica que entregue el lenguaje para describir el individualismo chileno como algo más que una simple categoría residual. Como se argumentará en la siguiente sección, la sociología del individuo podría bien servir como la puerta de entrada para este ejercicio. 

### Individualismo desde la Sociología del Individuo

Resulta algo sorprendente que en la literatura revisada en la sección anterior no se haga mención. Mal que mal, una forma de entender la individualización es como un individualismo institucionalizado: Esto es, como un proceso social en que "las instituciones cardinales de la sociedad moderna -- los derechos civiles, políticos y sociales básicos, pero también el empleo remunardo y la formación y movilidad que éste conlleva -- están orientado la individuo y no al grupo" [@beck2003, p. 32].

De forma suscinta, la teoría de la individualización surge en Europa a mediados de los años 80 para explicar las trasformaciones aparejadas a lo que se ha denominado como *modernidad reflexiva*, donde se observaría un proceso de distanciamiento entre agencia y estructura, dejando a un individuo cada vez más responsable de sí mismo y de dar respuestas las incertidumbres producidas en el mundo social [@beck2003]. Desde fines de los años 90, está teoría ha sido uno de los marcos analíticos preferidos por las ciencias sociales en Chile para dar cuenta de las transformaciones culturales, sociales y económicas producidas en el país durante las últimas décadas [@yopo2013]. 

El marco analítico de esta investigación se sostiene particularmente en el trabajo de Danilo Martuccelli, quien tanto en su obra individual [-@martuccelli2010;-@martuccelli2018], como en colaboración con Kathya Araujo [-@araujo2014;-@araujo2020;-@araujo2012], ha hecho esfuerzos contundentes para describir la forma particular del individualismo en Chile y América Latina. Tal como en la sección anterior se mostró la ambigüedad con que se definen los colectivos del colectivismo, a partir del trabajo de Martuccelli es posible revelar la noción de individuo que subyace a las conceptualizaciones clásicas de individualismo.

Martuccelli [-@martuccelli2010] argumenta que la representación del individuo que se volvió hegemónica para la modernidad es el individuo que es soberano es al menos dos acepciones. En primer lugar, porque se espera de este que sea dueño de sí mismo, independiente, autónomo y singular. En segundo lugar, porque es un ente racional capaz de legitimar el orden social y la soberanía colectiva.

Es este individuo quien se encuentra en el centro de un modelo de representación de la vida social que lo coloca en el centro del pacto social [@martuccelli2010; @martuccelli2018]. Es este modelo lo que clásicamente se entiende como individualismo. Un individualismo institucional, precisa Martuccelli [-@martuccelli2018] que se caracteriza por 3 rasgos fundamentales:

  - Una separación radical entre el holismo y el individualismo
  - Una concepciones atomizada del individuo. Es decir, la idea de los individuos son prexistentes de sus lazos sociales.
  - La preeminencia del rol de las instituciones en los procesos de individuación, de modo que la individualidad deja de ser percibida como una desviación y se convierte en el modelo institucional a encarnar. 
  
Las divergencias a este modelo observado en otras regiones del mundo, ha llevado normalmente a la negación de la existencia de individuos, individualización e individualismo en éstas [^1]. Como se menciono anteriormente, se esconde aquí un aspecto normativo que asocia al individualismo y al individuo soberano con el orden social moderno (occidental), y con la tradición a todas sus desviaciones [@martuccelli2018]. 

[^1]: Y también, como así precisa Martuccelli, a las mujeres, las diversidades sexuales o las personas con discapacidad. 

Abordar el fenómeno del individualismo desde la teoría de la individualización presenta la ventaja de que permite desembarazarse de esta conceptualización unívoca de individuo, así como de la ambigüedad y multiplicidad con que se define el colectivismo. Para ello, se propone una definición que permita conceptualizar el fenómeno para la sociedad chilena. 

Se entenderá como individualismo a los modelos de representación de la vida social que definen el rol del individuo en la sociedad. Bajo tales modelos, los individuos deben hacerse cargo de sus propias vidas en condiciones diversas de legitimidad de la acción individual, distintas representaciones culturales y autoconcepciones del individuo, y diferentes valores e imperativos estructuralmente producidos. 

Bajo este marco analítico, el colectivismo podría entenderse como un conjunto de modalidades de individualismo propias de sociedades en que la acción individual puede estar menos legitimada o en que los individuos construyen su identidad en torno a la pertenencia a una colectividad. En ningún, del tal modo, sería incompatible con la idea de individualismo, pues estas colectividades son grupos de libre elección conformadas por individuos que persiguen objetivos individuales a través de la acción colectiva [@arribas1999; @moemeka1998]. Zygmunt Bauman teoriza en este sentido, argumentando que los movimientos de trabajadores durante los siglos XIX y XX son resultado de procesos de individualización desiguales en esas sociedades:

> Las personas con menos recursos, y por tanto con menos elección, tenían que compensar esta carencia individual con la fuerza de los números, es decir, cerrando fiales y participando en acciones colectivas. Como ha dicho Claus Offe, la acción colectiva y orientada a la clase llegó a los que estaban en la parte baja de la escala social de manera tan *natural* y *obvia* como llegaba a sus jefes y empresarios la búsqueda individual de las metas vitales" [@bauman2003, p. 23].

Ya en la argumentación de Bauman se puede divisar un punto clave en este marco analítico: El individualismo institucional es solo una modalidad entre varias, con divergencias y difracciones. El propio Martuccelli [-@martuccelli2018] esquematiza una descripción de diversas variantes de individualismo que serían propias de las sociedades africanas (el individualismo comunitario), asiáticas (el individualismo ontorrelacional) y latinoamericanas (el individualismo agéntico). Pero, más interesante aún es que permite aprehender las difracciones dentro de una misma sociedad, y que esto es así incluso en las sociedades industriales en que emergió el modelo del individualismo institucional: El individualismo de los burgueses no era el mismo que el individualismo de los obreros. 


Las diferencias raciales en las escalas de individualismo-colectivismo en Estados Unidos [@oyserman2002; @komarraju2008] entregan evidencia empírica a esta forma de entender el constructo: Mientras entre europeos-estadounidenses no existe relación significativa entre individualismo y colectivismo, la asociación si es observable entre afroamericanos [@komarraju2008]. Se debe recordar, además, que ya en los años 80, en su clásico *Habits of the Hearts*, Robert Bellah y su equipo describían dos tradiciones de individualismo en los Estados Unidos. También en Chile, mediante un análisis de conglomerados a la escala de Triandis (que distingue entre individualismo-colectivismo vertical y horizontal), se lograron identificar 5 grupos (colectivistas independientes, colectivistas puros, colectivistas idiocéntricos, individualistas alocéntricos y renegados) [@rojas2008]. Pensar en distintas modalidades individualismo también permite dar una salida al problema del familiarismo identificado por Oyserman y colegas [-@oyserman2002] [^2]: No se trata de si el familiarismo es una característica propia del individualismo o del colectivismo, sino que hay individualismos que definen de forma diversa la relación del individuo con sus familias. 

[^2]: La misma lógica puede aplicar al problema de la jerarquía y la competencia también identificada en ese estudio [@oyserman2002].

En los párrafos que siguen, se dará -- brevemente -- algunas pequeñas precisiones sobre las dimensiones que se han identificado como componentes del fenómeno del individualismo:

#### Legitimidad de la Individualidad

Está dimensión se refiere a las creencias sobre la agencia de los individuos en el mundo social [@brewer2007], así como la valoración de la individualidad. Por individualidad aquí se entiende al "grado de diferenciación o de singularización reconocido o legítimamente alcanzado por un individuo dentro de un colectivo" [@martuccelli2018, p. 10].

Bajo el modelo del individualismo institucional, la individualidad deja de ser una anomalía para pasar a ostentar altos niveles de legitimidad [@martuccelli2018]. Sin embargo, esto se vería tensionado, por ejemplo, por la acentuación de conductas individualizadas sin ruptura de lazos comunitarios en sociedad africanas -- Modelo que Martuccelli [-@martuccelli2018] denomina como indivudalismo comunitario. Más cercano a la realidad nacional, Araujo y Martuccelli constantan que la individualidad ha sido históricamente visto con sospecha en sociedades latinoamericanas [@araujo2020a]. 

Ahora bien, se debe resaltar que el individualismo ha sido institucionalizado principalmente en 3 esferas: la económica, la política y la afectiva [@cortois2018; @martuccelli2018]. Esto se refleja en la existencia de 3 guiones para el individualismo institucional; en la esfera económica, un individualismo utilitario; en la política, un individualismo moral; y en la afectiva, un individualismo expresivo [@cortois2018]. Es importante hacer esta distinción, ya que en una misma sociedad pueden encontrtarse grupos e individuos que legitimen el individualismo en algunas esferas pero no en otras. Por ejemplo, en América del Norte se ha observado que grupos conservadores apoyan la determinación individual en la economía y en la elección de escuela, pero no en el derecho al aborto o a la eutanasia [@kemmelmeier2003].

El individualismo utilitario es aquel que entiende al individuo como propietario de su vid y sus habilidades, las que son susceptibles a ser intercambiadas en el libre mercado. La acción se entiende aquí como estratégica, es decir, como medios para conseguir fines individuales. El otro, de tal modo, no tiene un valor intrínseco, sino como un medio parat tales fines [@cortois2018]. En Chile, este tipo de individualismo podría asociarse a la instauración del neoliberalismo y la emergencia de un *homo neoliberalis*, pincipalmente mediante el acceso al consumo [@araujo2012; @araujo2020a]. Su legitimidad, con todo, está lejos de ser univoca, como se puede observar en la relación ambigua de los chilenos frente al oportunismo [@araujo2014] y frente al consumismo [@araujo2012].

El individualismo moral, en cambio, enfatiza la obligación moral de tratar al otro como un fin en sí mismo. La institucionalización de esta idea se puede observar en la declaraciones de derechos humanos, civiles y sociales, que reconocen a los individuos como iguales y autónomos [@cortois2018]. En América Latina, este tipo de individualismo ha se puede observar en la valorización de los derechos humanos tras las dictaduras del siglo XX [@araujo2020a]. En Chile, además, se podría observar en las aspiraciones por la democratización y horizontalización de lazo social, así como en las demandas por dignidad [@araujo2012].

Si cada una de estas variantes introducidas se puede relacionar con las dos vertientes de la *doble revolución* descrita por Eric Hobsbawm, Eva Illouz [-@illouz2020] introduce una tercera que aconteció en el plano emocional y en la esfera privada. Se trata de un cambio cultural del que emerge el individualismo expresivo, en el que la acción social se entiende como un medio para la autoexpresión auténtica del yo [@cortois2018]. Opera, así, en el ámbito del amor, la sexualidad, la identidad, las intimidad y la familia. Se distingue del individualismo utilitario en que, pese a que ambos están dirigidos hacia el propio individuo, el individualismo expresivo carece del carácter instrumental y estratégico del utilitarismo. Aunque en ese sentido podría acercarse al individualismo moral, la diferencia fundamental es que mientras este pone énfasis en la igualdad entre individuos ("todos los humanos nacen libres e iguales"), el expresivo le da relieve a la diferencia (particularmente, en la autenticidad y unicidad).

#### (Auto)concepciones del individuo

Esta dimensión aborda las diversas concepciones en torno a la que se pueden definir a las que se pueden definir las identidades de los individuos, ya sea como uno prexistente a sus relaciones sociales -- como ocurre bajo el modelo del individualismo institucional --, o bien como parte de sus relaciones sociales o grupos a los que pertenece [@brewer2007; @martuccelli2018]. 

Si bien la concepción de un individuo independiente se ha considerado como propio de las culturas individualistas [@benavides2020; @cross2011], tal idea ha sido problematizada teóricamente [@voronov2002] y empíricamente [@benavides2020; @kolstad2009]. Esto, junto a a la persistencia de los llamados valores asiáticos en esas sociedad, que conceptualizan al individuo como inseperable de sus lazos sociales [@zhai2022], y la conceptualización de un híper-actor relacional en la sociedad chilena [@araujo2020], sugiera la posibilidad de individualismos que difieren de las concepciones del individuo atomizado. 

Así, además de las autoconcepciones independientes se podrían identificar, por un lado, concepciones relaciones y concepciones colectivas [@brewer2007]. En las primeras, la identidad del individuo se define por sus relaciones cercanas, tales como la familia o los amigos. En las segundas, en tanto, es la identificaciones con grupos sociales más abstractos -- esto es, grupos nacionales, regionales, étnicos o religiosos -- lo que define a la identidad individual [@brewer2007]

#### Valores e Imperativos

Esta dimensión se refiere a la importancia relativa que se le otorga en una sociedad a diversos valores e imperativos individuales y colectivos [@brewer2007], los cuales son producidos por procesos sociohistóricos de individuación [@martuccelli2018]. Bajo el individualismo institucional, el principal valor para el individuo es la autonomía [@martuccelli2010]. Esto se realiza mediante un entramado institucional [@martuccelli2018] que "formula amablemente a cada uno que se constituya a sí mismo en individuo, que planifique su vida, diseñe y obre y asuma la responsabilidad en caso de fracaso" [@robles2001, p. 59]. Es, pues, una individuación reflexiva bajo la que los individuos se constituyen bajo el imperativo de ejercer control sobre sus destinos y tomar decisiones de manera autónoma [@silvapalacios2015], de ahí que su imperativo principal sea "vive tu vida como quieras" [@robles2001]

Sin embargo, también se han planteado visiones críticas a esta concepción, particularmente desde América Latina [@araujo2012; @robles2001]. No toda individuación sería reflexiva, ya que muchos individuos podrían experimentarla de forma delegativa, como una imposición [@silvapalacios2015]; no como un mundo de posibilidades, sino como lleno de incertidumbres. Los individuos, de tal modo, deben enfrentar las inseguridades ontológicas de la vida social a partir de sus propias habilidades bajo el imperativo de "arreglátelas como puedas" [@araujo2014; @robles2001]. Frente a esto, la valorización de la autonomía se vería desplazada por la búsqueda de seguridad como valor principal de esta forma de individuación [@silvapalacios2015]

## El Individualismo chileno

Se considera que no se cuentan con antecedentes empíricos suficientes como para establecer una hipótesis sobre los diversos perfiles de individualismo que pueden aparecer en la sociedad chilena. Sin embargo, teóricamente es posible inferir que el modelo predominante sería el del individualismo agéntico [@araujo2014]. En función a las dimensiones definidas, este se caracterizaría por: i) una alta legitimidad de la individualidad [@martuccelli2018], la que sin embargo podría ser menor en la esfera utilitaria como se podría extraer de la posición ambigua de los chilenas sobre acerca del oportunismo [@araujo2014] y el consumo [@araujo2012]; ii) Altos niveles de interdependencia relacional y grupal, dado el carácter relacional del individualismo chileno [@araujo2014], pero con niveles igualmente altos de concepciones independientes [@benavides2020; @kolstad2009]; iii) El desplazamiento de la autonomía como valor principal en favor de la búsqueda de seguridad, dado el énfasis en las destrezas personales de lo individuos como medio para superar las inseguridad ontológicas que deben enfrentar [@araujo2020a; @robles2001]


